server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location /api/events {
        proxy_pass http://event-service:8081/events;
        proxy_set_header Host $host;
    }

    location /api/users {
        proxy_pass http://user-service:8000/users;
        proxy_set_header Host $host;
    }

    location /api/notifications {
        proxy_pass http://notification-service:8000/notifications;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
